- 1.13CommandAPI/src/io/github/jorelali/commandapi/api/SemiReflector.java
Wrote some command code that had a NullPointerException - but had no way to figure out where it was (nothing in the log, just a failed command). 
This small snippet of code dumps a stacktrace to the log when a custom command throws an exception to help with debugging.
> Add exception handling & stacktrace for failed commands

- 1.13CommandAPI/src/io/github/jorelali/commandapi/api/exceptions/WrapperCommandSyntaxException.java
This preserves backwards compatibility for users who were catching a CommandSyntaxException and displaying the exception message by allowing them to only swap references of CommandSyntaxException to WrapperCommandSyntaxException without further code changes.
It might be worth overriding other Throwable methods to do the same thing.
> Override the getMessage function

- commandapi-core/src/main/java/dev/jorel/commandapi/CommandAPIHandler.java
`CommanAPIHandler#parseArgument` is called in two places, `CommandAPIHandler#argsToObjectArr` and `CommandAPIHandler#generatePreviousArguments`. Previously, `parseArgument` called `generatePreviousArguments` to get the objects associated with the previous arguments in case they were needed. Since `generatePreviousArguments` goes back and calls `parseArgument`, this can cause arguments to be parsed multiple times like so:
```
argsToObjectArr -> I need to parse args [1, 2, 3]
1:
parseArgument -> I need previous args for 1
generatePreviousArguments -> There are none
1 is parsed
2:
pA -> I need previous args for 2
gPA -> I need to parse arg 1
pA -> I need previous args for 1
gPA -> There are none
1 is parsed
2 is parsed
3:
pA  -> I need previous args for 3
gPA -> I need to parse args 1, 2
pA …
```
> Avoid re-parsing arguments in CommandAPIHandler#parseArgument

- commandapi-core/src/main/java/dev/jorel/commandapi/CommandAPI.java
Adds isLoaded method to CommandAPI.java to avoid getting "You've tried to call the CommandAPI's onLoad() method more than once!".
> isLoaded method

- commandapi-core/src/main/java/dev/jorel/commandapi/arguments/ListArgument.java
- commandapi-core/src/main/java/dev/jorel/commandapi/arguments/ListArgumentBuilder.java
- commandapi-plugin/src/main/java/dev/jorel/commandapi/CommandAPIMain.java
The focus of this PR is to improve the ListArgument's suggestions. Using brigadier's `SuggestionBuilder#createOffset` items can be suggested one at a time, which makes it more clear what the next item is. If an argument is completed this code also suggests the deliminator, making it clear to the user how the command wants them to separate the arguments.
As a minor addition, the ListArgumentBuilder was given the method `withList(T... array)`, which automatically wraps an array into a list. I think this is cleaner on the developer side since they don't need to put `List.of()` themselves. Regardless, it's just a minor change, so you can keep it or leave it.
> Improve ListArgument

- commandapi-core/src/main/java/dev/jorel/commandapi/arguments/ListArgument.java
- commandapi-plugin-test/src/test/java/ArgumentTests.java
Adding one last change to the ListArgument I forgot for #319, this PR enforces the ListArgument's syntax by throwing CommandSyntaxExceptions. Previously, the ListArgument would ignore items that weren't in its list and move on. If the list didn't allow duplicates, it would also just add one of each item. Now, a CommandSyntaxException will be thrown in those cases.
I think the changes to the test cases best explain this:
```java
server.dispatchCommand(sender, "list cat, wolf, axolotl"); // normal list
server.dispatchCommand(sender, "list cat, wolf, axolotl, wolf"); // don't allow duplicates
server.dispatchCommand(sender, "list axolotl, wolf, chicken, cat"); // don't allow unknown items
```
This list command does not allow duplicates. The first command works. The second command complains …
> Throw CommandSyntaxExceptions when ListArgument input is wrong

- commandapi-core/src/main/java/dev/jorel/commandapi/CommandAPI.java
- commandapi-nms/commandapi-1.19-common/src/main/java/dev/jorel/commandapi/nms/NMS_1_19_Common_ChatPreviewHandler.java
- commandapi-nms/commandapi-1.19.1/src/main/java/dev/jorel/commandapi/nms/NMS_1_19_1_R1_ChatPreviewHandler.java
- commandapi-nms/commandapi-1.19/src/main/java/dev/jorel/commandapi/nms/NMS_1_19_R1_ChatPreviewHandler.java
The focus of this PR is the added class `NMS_1_19_Common_ChatPreviewHandler`. `NMS_1_19_R1_ChatPreviewHandler` and `NMS_1_19_1_R1_ChatPreviewHandler` extend this class, and it handles things like intercepting chat preview packets and converting the chatPreviewQuery into JSON, which was previously duplicated across those two classes. Along with reorganizing some of the code, these changes saved ~2.4 kB from the plugin jar and made the code easier to understand.
In the future, I think that `NMS_1_19_Common_ChatPreviewHandler` will be able to be adapted for new versions. The only line that looks problematic is 
```java
this.connection = ((CraftPlayer) player).getHandle().connection.connection;
```
which accesses `org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer`. Other than that, …
> Share and simplify ChatPreviewHandler code

- commandapi-core/src/test/kotlin/Examples.kt
I sadly forgot to add the `.register()` methods to the examples in `Examples.kt` which is why I am doing this now.
I will do better next time, I promise.
> add missing .register() methods in Example.kt

- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/CommandAPIBukkit.java
The title is not great, I know and it can be misunderstood!
In my plugin, I register a command permission. LuckPerms also registers a command permission.
The CommandAPI does this:
`[01:15:12 WARN]: [CommandAPI] Plugin command /permission is registered by Bukkit (LuckPerms). Did you forget to remove this from your plugin.yml file?`
This PR makes it so that the CommandAPI doesn't complain about plugin commands registered in a `plugin.yml` if the `plugin.yml` doesn't belong to the plugin calling the CommandAPI.
> Make the CommandAPI complain less about command registered in the plugin.yml

- commandapi-core/src/main/java/dev/jorel/commandapi/executors/CommandArguments.java
Adds CommandArguments#count() utility method to get the number of arguments.
> Add utility getter for argument count on CommandArguments object

- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/arguments/AdventureChatComponentArgument.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/arguments/ChatComponentArgument.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-test/commandapi-bukkit-test-tests/src/test/java/dev/jorel/commandapi/test/arguments/ArgumentBlockStateTests.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-test/commandapi-bukkit-test-tests/src/test/java/dev/jorel/commandapi/test/arguments/ArgumentItemStackTests.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-test/commandapi-bukkit-test-tests/src/test/java/dev/jorel/commandapi/test/arguments/ArgumentLocationTests.java
- docssrc/src/argument_blockpredicate.md
- docssrc/src/argument_chat_adventure.md
- docssrc/src/argument_chat_spigot.md
- docssrc/src/argument_chats.md
- docssrc/src/argument_entities.md
- docssrc/src/argument_itemstackpredicate.md
- docssrc/src/argument_namespacedkey.md
- docssrc/src/argument_particle.md
- docssrc/src/argument_scoreboards.md
- docssrc/src/conversionentityselectors.md
- docssrc/src/conversionforownerssingleargs.md
- docssrc/src/functions.md
The Minecraft Wiki maintainers have decided to move away from Fandom. More information can be found here: <https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom>. This PR updates all the URLs to the new domain: minecraft.wiki
> Update Minecraft Wiki links to new domain after fork

- docssrc/src/commandregistration.md
Fixing the small typo: **`When`**`, we create...` to **`Then`**`, we create...`
> Typo fix in Command registration

- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/BukkitTooltip.java
- docssrc/src/upgrading.md
Not sure if I need to put `since = "..."`
> Fix 'advenure' typos

- .editorconfig
- commandapi-documentation-code/pom.xml
- commandapi-documentation-velocity-code/pom.xml
- commandapi-documentation-velocity-code/src/main/java/dev/jorel/commandapi/examples/java/Examples.java
- commandapi-documentation-velocity-code/src/main/kotlin/dev/jorel/commandapi/examples/kotlin/Examples.kt
- docssrc/src/SUMMARY.md
- docssrc/src/velocity_intro.md
- pom.xml
This is supposed to add a bit of Velocity documentation to the documentation.
Feel free to suggest anything else that you think should be added!
> Velocity Documentation

- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/CommandAPIBukkit.java
The basic thing works, just a few more things need checking:
> Fix help topic generation

- README.md
- commandapi-core/src/main/java/dev/jorel/commandapi/executors/CommandArguments.java
- commandapi-documentation-code/src/main/java/dev/jorel/commandapi/examples/java/Examples.java
- commandapi-documentation-code/src/main/kotlin/dev/jorel/commandapi/examples/kotlin/Examples.kt
- docssrc/src/commandarguments.md
- docssrc/src/intro.md
This PR is supposed to implement certain methods as suggested by Hawk [here](https://discord.com/channels/745416925924032523/745419648970784821/1218161950865883198) and by #535.
Currently, there is a bit more testing I want to do, additionally I am not sure if this would actually be something we want.
If so, there is a bit more work required:
> Implement "safe-casting"

- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-nms/commandapi-bukkit-1.20.5/src/main/java/dev/jorel/commandapi/nms/NMS_1_20_R4.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-nms/commandapi-bukkit-nms-common/src/main/java/dev/jorel/commandapi/nms/NMS_Common.java
Some of this is not pretty but doing this the VarHandle-less way also got rid of the exception in the console which I didn't seem to do with VarHandles.
Nevertheless, this should make it possible to at least register commands using Paper 1.20.6 build 65 and onwards.
I plan to handle all this properly in #517
> Hotfix CommandAPI throwing errors because of Paper's Brigadier command API

- docssrc/src/setup_shading.md
Makes the documentation be specific about using Goooler's fork of the gradle shadow plugin, as it broke with Java 21.
> Modify gradle shadow plugin to use Goooler's fork for Java 21 support (Issue #567)

- docssrc/src/arguments.md
Fixed a grammatical mistake in arguments.md at line 20 in the second sentence. More specifically there was a duplicate 'is' word.
> Fix grammatical mistake

- README.md
- commandapi-core/src/main/java/dev/jorel/commandapi/CommandAPI.java
- commandapi-core/src/main/java/dev/jorel/commandapi/CommandAPIConfig.java
- commandapi-core/src/main/java/dev/jorel/commandapi/CommandAPIVersionHandler.java
- commandapi-core/src/main/java/dev/jorel/commandapi/InternalConfig.java
- commandapi-core/src/main/java/dev/jorel/commandapi/LoadContext.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-plugin-mojang-mapped/src/main/java/dev/jorel/commandapi/CommandAPIMain.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-plugin-mojang-mapped/src/main/resources/config.yml
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-plugin/src/main/java/dev/jorel/commandapi/CommandAPIMain.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-plugin/src/main/resources/config.yml
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-test/commandapi-bukkit-kotlin-test/src/test/kotlin/dev/jorel/commandapi/CommandAPIVersionHandler.kt
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-test/commandapi-bukkit-test-tests/src/test/java/dev/jorel/commandapi/CommandAPIVersionHandler.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-vh/src/main/java/dev/jorel/commandapi/CommandAPIVersionHandler.java
- commandapi-platforms/commandapi-bukkit/pom.xml
- commandapi-platforms/commandapi-velocity/commandapi-velocity-core/src/main/java/dev/jorel/commandapi/CommandAPIVersionHandler.java
- docssrc/src/config.md
- docssrc/src/setup_shading.md
Currently, when updating to *any* new Minecraft version that is not currently supported, we throw an `UnsupportedVersionException`.
This is not that great since even minor updates require an update to not throw that exception.
This pull request enables, when setting the config option, an update to minor versions of the game:
- An update from 1.21.1 to 1.21.2 would be allowed
- An update from 1.21.2 to 1.22 would still result in an `UnsupportedVersionException` since presumably we still want to double check compatibility for major versions.
**So why the new config option when we have the option of just loading the latest NMS version?**
Well, the latest NMS version completely breaks support for older versions, this only does something when a server version is used that the main part of …
> Be more lenient with version checks when updating the minor version of the game

- commandapi-codecov/pom.xml
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-plugin-common/src/main/java/dev/jorel/commandapi/CommandAPIMain.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-plugin-common/src/main/java/dev/jorel/commandapi/config/BukkitConfigurationAdapter.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-test/commandapi-bukkit-test-tests/pom.xml
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-test/commandapi-bukkit-test-tests/src/test/java/dev/jorel/commandapi/test/ConfigGenerationTests.java
- commandapi-platforms/commandapi-velocity/commandapi-velocity-plugin/src/main/java/dev/jorel/commandapi/CommandAPIMain.java
- commandapi-platforms/commandapi-velocity/commandapi-velocity-plugin/src/main/java/dev/jorel/commandapi/config/VelocityConfigurationAdapter.java
- commandapi-plugin/src/main/java/dev/jorel/commandapi/config/ConfigGenerator.java
- commandapi-plugin/src/main/java/dev/jorel/commandapi/config/ConfigurationAdapter.java
Small follow-up for #596 because I was too quick
> Rework plugin config system #2

- commandapi-core/src/main/java/dev/jorel/commandapi/AbstractArgumentTree.java
- commandapi-core/src/main/java/dev/jorel/commandapi/AbstractCommandTree.java
- commandapi-kotlin/commandapi-bukkit-kotlin/src/main/kotlin/dev/jorel/commandapi/kotlindsl/CommandTreeDSL.kt
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-test/commandapi-bukkit-kotlin-test/src/test/kotlin/dev/jorel/commandapi/test/dsltests/CommandTreeTests.kt
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-test/commandapi-bukkit-test-tests/src/test/java/dev/jorel/commandapi/test/CommandRegistrationTests.java
- docssrc/src/commandtrees.md
Implemented the feature in #529 with Kotlin DSL support and changed the method name to 'thenNested' as suggested [in Discord](https://discord.com/channels/745416925924032523/745418987948736543/1304125456005595208)
Usage: 
<details>
<summary>Java: </summary>
```java
new CommandTree("example")
.thenNested(
new LiteralArgument("arg1"),
new StringArgument("arg2"),
new StringArgument("arg3"),
new DoubleArgument("arg4", 0),
new StringArgument("arg5")
.executes(...)
) 
```
</details>
<details>
<summary> Kotlin: </summary>
```kotlin
CommandTree("example")
.thenNested(
LiteralArgument("arg1"),
StringArgument("arg2"),
StringArgument("arg3"),
DoubleArgument("arg4", 0),
StringArgument("arg5")
.executes { ... }
)
```
</details>
<details>
<summary> Kotlin DSL</summary>
```kotlin
commandTree("example") …
```
> Implement NestedArguments (#529)

- README.md
After the repository is moved, the URL in the readme needs to be modified, otherwise some tags will not work
> fix repo URL in readme

- README.md
- commandapi-annotations/src/main/java/dev/jorel/commandapi/annotations/Annotations.java
- commandapi-annotations/src/main/java/dev/jorel/commandapi/annotations/arguments/AAsyncOfflinePlayerArgument.java
- commandapi-core/src/main/java/dev/jorel/commandapi/arguments/CommandAPIArgumentType.java
- commandapi-kotlin/commandapi-bukkit-kotlin/src/main/kotlin/dev/jorel/commandapi/kotlindsl/CommandAPICommandDSL.kt
- commandapi-kotlin/commandapi-bukkit-kotlin/src/main/kotlin/dev/jorel/commandapi/kotlindsl/CommandTreeDSL.kt
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/arguments/AsyncOfflinePlayerArgument.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-plugin-common/src/main/java/dev/jorel/commandapi/AdvancedConverter.java
This pull request introduces the `AsyncOfflinePlayerArgument`, which extends the `SafeOverrideableArgument` class. The new class wraps the existing `OfflinePlayerArgument` within a `CompletableFuture<OfflinePlayer>`, enabling asynchronous handling of the offline player argument in commands. By using this approach, the logic involving API calls to fetch the offline player will be executed off the main thread, reducing the risk of blocking the server's main thread and improving performance.
See https://github.com/CommandAPI/docs/pull/1
This PR is in continuation of #632, which I accidentally closed :-)
> [Feat] AsyncOfflinePlayerArgument

- README.md
- commandapi-core/src/main/java/dev/jorel/commandapi/ExecutableCommand.java
- commandapi-core/src/main/java/dev/jorel/commandapi/RegisteredCommand.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/CommandAPIBukkit.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/PaperCommandRegistration.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/PaperImplementations.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-nms/commandapi-bukkit-1.20.5/src/main/java/dev/jorel/commandapi/nms/NMS_1_20_R4.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-nms/commandapi-bukkit-1.21.2/src/main/java/dev/jorel/commandapi/nms/NMS_1_21_R2.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-nms/commandapi-bukkit-1.21.4/src/main/java/dev/jorel/commandapi/nms/NMS_1_21_R3.java
- commandapi-platforms/commandapi-bukkit/commandapi-bukkit-nms/commandapi-bukkit-1.21/src/main/java/dev/jorel/commandapi/nms/NMS_1_21_R1.java
Fixes #583
Fixes #578 
The behaviour for #578 is unexpected, but corect. After this PR, instead of returning the wrong permission, `getCommandMap("commandname").getPermission()` will return `null`. This is the correct behaviour which can easily be verified if you follow the initialization chain starting here: https://github.com/PaperMC/Paper/blob/09f1f88f58a03f61092f8636ad780d42db87d8d9/paper-server/src/main/java/io/papermc/paper/command/brigadier/PaperBrigadier.java#L49
> Register commands as plugin commands on Paper 1.20.6 and above
